# -*- coding: utf-8 -*-
"""visual_truths_inflation_case_study.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ohS8F0oC796u3IJkYCp9gi9ZsJ-gBTPG
"""

from google.colab import files

uploaded = files.upload()

import zipfile
import os

# Get uploaded filename automatically
zip_filename = list(uploaded.keys())[0]

extract_path = "world_bank_inflation"
os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_filename, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

os.listdir(extract_path)

for file in os.listdir(extract_path):
    print(file)

import pandas as pd

data_file = [
    f for f in os.listdir(extract_path)
    if f.startswith("API_") and f.endswith(".csv")
][0]

file_path = os.path.join(extract_path, data_file)

df = pd.read_csv(file_path, skiprows=4)
df.head()

# Select recent years with reliable data
years = [str(y) for y in range(2015, 2023)]

india_df = df[df["Country Name"] == "India"][years].T
india_df.columns = ["Inflation"]
india_df.index.name = "Year"

# Drop NaNs only for plotting
india_df = india_df.dropna()

india_df

import matplotlib.pyplot as plt

plt.figure(figsize=(7,4))
plt.plot(india_df.index, india_df["Inflation"], marker='o')
plt.ylim(4, 8)  # intentionally misleading scale
plt.title("Inflation Trend in India (Misleading Scale)")
plt.xlabel("Year")
plt.ylabel("Inflation (%)")
plt.grid(True)
plt.show()

plt.figure(figsize=(7,4))
plt.plot(india_df.index, india_df["Inflation"], marker='o')
plt.ylim(0, india_df["Inflation"].max() + 1)
plt.title("Inflation Trend in India (Corrected Scale)")
plt.xlabel("Year")
plt.ylabel("Inflation (%)")
plt.grid(True)
plt.show()

countries = ["India", "United States", "China"]
year = "2022"

compare_df = df[df["Country Name"].isin(countries)][
    ["Country Name", year]
].dropna()

compare_df

plt.figure(figsize=(6,4))
plt.bar(compare_df["Country Name"], compare_df[year])
plt.title(f"Inflation Comparison Across Countries ({year})")
plt.xlabel("Country")
plt.ylabel("Inflation (%)")
plt.grid(axis='y')
plt.show()

# Misleading graph
plt.figure(figsize=(7,4))
plt.plot(india_df.index, india_df["Inflation"], marker='o')
plt.ylim(4, 8)
plt.title("Inflation Trend in India (Misleading Scale)")
plt.xlabel("Year")
plt.ylabel("Inflation (%)")
plt.savefig("misleading_graph.png", bbox_inches="tight")
plt.close()

# Corrected graph
plt.figure(figsize=(7,4))
plt.plot(india_df.index, india_df["Inflation"], marker='o')
plt.ylim(0, india_df["Inflation"].max() + 1)
plt.title("Inflation Trend in India (Corrected Scale)")
plt.xlabel("Year")
plt.ylabel("Inflation (%)")
plt.savefig("corrected_graph.png", bbox_inches="tight")
plt.close()

# Comparative bar chart
plt.figure(figsize=(6,4))
plt.bar(compare_df["Country Name"], compare_df[year])
plt.title(f"Inflation Comparison Across Countries ({year})")
plt.xlabel("Country")
plt.ylabel("Inflation (%)")
plt.savefig("comparative_bar_chart.png", bbox_inches="tight")
plt.close()